### ISSUE TITLE
Create ZFS Provider

### ISSUE THREAD

**Issue by pjnorton** [mistifyio/mistify#40]
Create a provider for ZFS.

**Comment by bbickerton** [comment]
Going to need to resolve https://github.com/mistifyio/gozfs/issues/20 first. Need a public API around zfs.

**Comment by bbickerton** [comment]
Exists, Destroy, and Create (mostly) done. There's an issue with zfs commands that accept properties that I need to find a good solution for.

Several of the zfs ioctl API commands take a "props" property: clone, create, snapshot. I have had problems in the past using a full set of properties (i.e. a dataset properties struct), where both struct field defaults and irrelevant properties cause the zfs command to fail. Instead, I am passing a dynamic set of properties, just the ones explicitly set, using a `map[string]interface{}`. Unmarshalling JSON into a `map[string]interface{}` treats all numbers as `float64` by default, while zfs expects them to be `uint64`.

The solution I am considering is to loop over the map, check whether the value has a numeric type, and replace them with values cast to `uint64`. I need to first check whether anything other than uint64 is supported for numeric values in user defined properties.

**Comment by bbickerton** [comment]
A lot of progress on this and gozfs today. All that remains is `Send` and a few tweaks.

**Comment by bbickerton** [comment]
Got `Send` working and made some updates to `gozfs`. Need to add streaming request support to `acomm` to stream data to providers (for `Receive`)

**Comment by bbickerton** [comment]
Finished provider. Writing tests.

**Comment by bbickerton** [comment]
Wrote most tests. Working on Send/Receive tests.

**Comment by bbickerton** [comment]
Finished tests. 89.2% code coverage.
