### ISSUE TITLE
Add Jenkins slave to Docker container

### ISSUE THREAD

**Issue by pjnorton** [mistifyio/mistify#61]
# Issue Description

From 3/22 planning session with StevenIsaacs.  Once he is able to successfully build Mistify OS within  a Mistify OS based Docker container, add a Jenkins slave to the container.
# Acceptance Criteria (How do we know when this is done?)

Jenkins slave runs in a docker container where Mistify OS has been built.
# Related Tickets
#36 Get Mistify OS to build in a Mistify OS based Docker container

**Comment by StevenIsaacs** [comment]
Running a Jenkins slave requires Java. I added this to the SDK docker container along with the script to start a Jenkins slave. I've manually verified this process works and the slave connects to the Jenkins Master running on AWS. Jobs have not yet been sent to the Jenkins slave to verify it can actually build MistifyOS.
